import type { InsightsResponse } from "../lib/types";
import { categoryLabel, formatKg } from "../lib/format";

interface Props {
  insights: InsightsResponse;
}

const SOURCE_LABELS: Record<InsightsResponse["source"], string> = {
  gemini: "AI-personalized",
  rules: "Smart rules",
  cache: "Cached insight",
};

/** Personalized summary + ranked, quantified reduction actions. */
export function InsightsPanel({ insights }: Props) {
  const sourceLabel = SOURCE_LABELS[insights.source];

  return (
    <section className="card" aria-labelledby="insights-heading">
      <h2 id="insights-heading">
        Personalized insights{" "}
        <span className="badge" aria-label={`Generated by ${sourceLabel}`}>
          {sourceLabel}
        </span>
      </h2>

      <p>{insights.summary}</p>

      <h3>Recommended actions</h3>
      <ul className="plain-list">
        {insights.recommendations.map((rec, i) => (
          <li className="recommendation" key={`${rec.category}-${i}`}>
            <strong>{categoryLabel(rec.category)}:</strong> {rec.action}
            <div className="saving">
              Potential saving: {formatKg(rec.estimated_annual_savings_kg)} CO₂e / year
            </div>
          </li>
        ))}
      </ul>
    </section>
  );
}
